@TicketToCode.Api_HostAddress = https://localhost:7206

GET {{TicketToCode.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{TicketToCode.Api_HostAddress}}/auth/login
Content-Type: application/json

{
  //Request
}

###

POST {{TicketToCode.Api_HostAddress}}/auth/register
Content-Type: application/json

{
  //Request
}

###
